import React from 'react';
import { useParams } from "react-router-dom";
import Header from '../components/Header';
import '../styles/Report.css';

const Report = () => {
    const { id } = useParams();

    switch(id) {
        case '1':
            return(
                <>
                    <Header page={'report'} report={{id, desc: 'Application Developer - Kenna'}}/>
                    <div className='main_wrapper reports'>
                        <h2>Introduction 👋</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hello, I am Burak and I am a 3rd year Computer Science Co-op student at the University of Guelph. In this work term report, I will share my experiences working at Kenna as an application developer for 4 months, which was my first co-op, highlighting what I've learned and how I accomplished my goals.</p>
                        <h2>Information about Kenna 📍</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kenna is a marketing solutions company located in Mississauga, Ontario helping a number of client companies by providing them software, data management solutions/systems since 1985. The team I worked with, the application dev team, designs and maintains many web applications for a client which is the part that is related to my major, computer science.</p>
                        <h2>Job Description 📖</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My main task during this term was to maintain and add new software features like APIs, front-end code, SQL stored procedures to a retailer website according to the business requirements and quality assurance items of the account team. The technologies I used were IBM Domino, Microsoft SQL, React.js, Node.js and many other smaller frameworks. The tasks varied from front-end to back-end with more focus to front-end. While maintaining and adding new features/sub-applications for the retailer website was my main task, I also worked on migrating that website from the legacy frameworks to more modern frameworks using React and Node, which I found to be more interesting. I knew the basics of the technologies and the transferable skills that were required for this job before starting, and learned more and got better as I went along so I can safely say that this co-op experience definitely enhanced my academic experience as well. I also think I was able to accomplish the goals I set for myself when I first started which I will talk about in more detail in the next section.</p>
                        <h2>Goals 🎯</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My first goal was improving my technological literacy and I believe that I was mostly able to learn/improve on the technologies I wanted during this work term. I mostly did front end tasks, specifically React.js and HTML/CSS but I was able to do some back end (SQL, Node.js) as well. For example, one of the big tasks I worked on was migrating a legacy app to modern frameworks which really improved my React, Node and SQL skills. Another task I worked on was implementing a redirection system for new users to a course website, which again required me to utilize my Node and React skills. Overall, I was able to do all of the tasks that I was assigned without any issues, and I got better during this process, and I believe I am a lot more knowledgeable on fullstack development than I first started.</p>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Another goal I had was improving my oral communication skills which I think is important in any field and I believe that I was able to improve a lot in terms of this goal. I was able to do the tasks I was assigned successfully and during the process I communicated with not only my supervisor but a lot of other people from the account team to make sure I was doing everything right. I attended briefings for the projects, asked questions and gave my opinions and received good feedback in the end.</p>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My last goal was about improving my problem solving skills which I think is very important especially in software development. Most of the tasks I worked on during this work term required me to use my problem solving skills as they were programming related tasks. The more I did them, the better I got, and I was able to reflect on what I've learned to come up with the best solutions. For example, the react migration task I mentioned before required me to come up with a structure for the components that was abstract so that it would work optimally with different pages. I also was able to fix an issue that we faced with the Node.js server which required me to investigate and identify the problems in the app. Overall, I was able to come up with good solutions and fix the problems successfully and now I believe I am a better problem solver/programmer than I was when I first started.</p>
                        <h2>Conclusion 🔚</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In the end, I can easily say that I had a great time with Kenna, accomplished all of my goals, have one more great experience to put on my resume and learned a lot about technologies such as React, Node APIs and SQL databases, transferable skills such as communication, problem solving and overall software development processes in a professional business environment and I believe these will help me a lot in my future careers and academics. I definitely couldn't have asked for a better first co-op.</p>
                        <h2>Acknowledgements 🏆</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I first would like to thank my supervisor Kishan for teaching and helping me with all of the technologies I used during my work term. I think without him, everything would have been a lot more difficult. I also would like to thank Kenna for giving me a chance for this co-op term. Lastly, I would like to thank my co-op coordinators Laura and Kate, they were really helpful during the hiring process and answered all my questions, everything was clear going into this work term thanks to them.</p>
                    </div>
                </>
            );
        case '2':
            return(
                <>
                    <Header page={'report'} report={{id, desc: 'Application Developer - Kenna'}}/>
                    <div className='main_wrapper reports'>
                        <h2>Introduction 👋</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hello, I am Burak and I am a 4th year Computer Science Co-op student at the University of Guelph. In this work term report, I will share my experiences working at Kenna as an application developer for 4 months, which was my second co-op with them, highlighting what I've learned and how I accomplished my goals.</p>
                        <h2>Information about Kenna 📍</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kenna is a marketing solutions company located in Mississauga, Ontario helping a number of client companies by providing them software, data management solutions/systems since 1985. The team I worked with, the application dev team, designs and maintains many web applications for a client which is the part that is related to my major, computer science.</p>
                        <h2>Job Description 📖</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My main tasks during this term was similar to my previous term. Things I had to do was to maintain and add new software features like APIs, front-end code, SQL stored procedures to a grower website according to the business requirements and quality assurance items of the account team. The technologies I used were IBM Domino, Microsoft SQL, React.js, Node.js, jQuery and many other smaller frameworks. The tasks varied from front-end to back-end equally. While maintaining and adding new features/sub-applications for the grower website was my main task, I also worked on migrating that website from the legacy frameworks to more modern frameworks using SQL and Node. I already had some grasp on the technologies and the transferable skills that were required for this job before starting, thanks to my previous term. But I definitely learned more and got better as I went along so I can safely say that this co-op experience definitely enhanced my academic experience as well. I also think I was able to accomplish the goals I set for myself when I first started which I will talk about in more detail in the next section.</p>
                        <h2>Goals 🎯</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My first goal was improving my technological literacy even further and I believe that I was able to improve on the technologies I wanted during this work term. I did both front end and back end tasks, specifically jQuery, SQL and Node.js. For example, one of the big tasks I worked on was migrating a legacy app's backend to modern frameworks like SQL and Node which really improved my skills on those technologies. Another relevant task I worked on was figuring out a way to secure a web app's email submitting functionality after a cyber attack which required me to do research on captchas and improved my Node.js skills as I had to implement it on the backend. Overall, I was able to do all of the tasks that I was assigned without any issues, and I got better during this process, and I believe I am a lot more knowledgeable on fullstack development than I first started.</p>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Another goal I had was improving my written communication skills which I think is important in any field and I believe that I was able to improve a decent amount in terms of this goal too. I was able to do the tasks I was assigned successfully and during the process I communicated with not only my supervisor but a lot of other people from the account team to make sure I was doing everything right. I utilized the jira system and microsoft teams to ask questions and give my opinions and received good feedback in the end.</p>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My last goal was about improving my time management skills which, again, I think is very important in any field. The tasks I worked on during this work term required me to manage my time effectively. When I first started, after a long study term, I was washed up on this skill and was rather disorganized however I was quickly able to imrpove. For example, when I was working on the migration tasks, I could only migrate 1-2 functions a day. But the more I worked on this and started to plan out what to do, this number quickly got up to around 4-5. Overall, having a schedule and planning out what to do in a work day incresed my efficieny drastically, and now I believe I am a lot better at managing my time than I was when I first started.</p>
                        <h2>Conclusion 🔚</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To sum up, I can easily say that I had a great second co-op term with Kenna, accomplished all of my goals, have one more great experience to put on my resume and learned a lot more about the technologies I mentioned such as Node APIs and SQL databases, transferable skills such as communication, time management and overall software development processes in a professional business environment and I believe these will help me a lot in my future careers and academics.</p>
                        <h2>Acknowledgements 🏆</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I first would like to thank my supervisors Amirul and Anusha for teaching and helping me with all of the technologies I used during my work term. I also would like to thank Kenna for giving me a return offer for this co-op term. Lastly, I would like to thank my co-op coordinators Laura and Kate, they were really helpful during the hiring process and answered all my questions, everything was clear going into this work term thanks to them.</p>
                    </div>
                </>
            );
        case '3':
            return(
                <>
                    <Header page={'report'} report={{id, desc: 'Application Developer - Kenna'}}/>
                    <div className='main_wrapper reports'>
                        <h2>Introduction 👋</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hello, I am Burak and I am a 4th year Computer Science Co-op student at the University of Guelph. In this work term report, I will share my experiences working at Kenna as an application developer for the first 4 months of an 8 month term, which was my third co-op with them, highlighting what I've learned and how I accomplished my goals.</p>
                        <h2>Information about Kenna 📍</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kenna is a marketing solutions company located in Mississauga, Ontario helping a number of client companies by providing them software, data management solutions/systems since 1985. The team I worked with, the application dev team, designs and maintains many web applications for a client which is the part that is related to my major, computer science.</p>
                        <h2>Job Description 📖</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My main tasks during this term was similar to my previous terms. Things I had to do was to maintain and add new software features like APIs, frontend code, SQL stored procedures to a grower website and various campaign sites according to the business requirements and quality assurance items of the account team. This term however I also had the chance to develop a web application from scratch including its DB design, backend/frontend code. The technologies I used were TypeScript, Redux, MSSQL, React.js, Node.js and many other smaller frameworks. The tasks varied from frontend to backend equally. While maintaining and adding new features/sub-applications for these websites was my main task, I also worked on migrating the frontend of that website from the legacy frameworks to more modern frameworks using TS and React/Redux. I already had some grasp on the technologies and the transferable skills that were required for this job before starting, thanks to my previous terms. But I definitely learned more and got better as I went along so I can safely say that this co-op experience definitely enhanced my academic experience as well. I also think I was able to accomplish the goals I set for myself when I first started which I will talk about in more detail in the next section.</p>
                        <h2>Goals 🎯</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My first goal was to enhance my technological literacy, with a particular focus on backend technologies like Node, SQL Server, and various design patterns. Throughout this work term, I tackled numerous tasks and QA tickets that incorporated these technologies. For example, one of the major projects I undertook required me to learn and utilize TypeScript and Redux. Another one, which I already mentioned was creating a web app from scratch which included me to work with backend technologies. By the end of the term, I could complete tasks involving these technologies faster and with fewer errors. I believe I have significantly improved my skills in this area compared to when I first started.</p>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Another goal I set was to improve my inquiry and analysis skills, especially for larger-scale tasks, to ensure effective communication with the team and successful task completion. Throughout this term, I consistently engaged with tasks that required deep reflection and problem-solving. By reflecting on what I learned and communicating effectively with the team, I contributed to generating better solutions, identifying and addressing problems efficiently, and successfully completing all my tasks. I believe my inquiry and analysis skills have improved considerably.</p>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My final goal was to enhance my teamwork abilities, particularly in collaborating with others and dividing work to complete tasks successfully. This term, I worked on several projects that required significant collaboration. For instance, during the big migration task and some smaller application developments, teamwork played a crucial role. Compared to previous terms, I had more opportunities to collaborate with my colleagues, effectively splitting up the work and communicating efficiently. I believe I have made substantial progress in improving my teamwork skills.</p>
                        <h2>Conclusion 🔚</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To sum up, I can easily say that I had a great co-op term with Kenna, accomplished all of my goals, have one more great experience to put on my resume and learned a lot more about the technologies I mentioned such as TypeScript, Redux and MSSQL, transferable skills such as teamwork, inquiry & analysis and overall software development processes in a professional business environment and I believe these will help me a lot in my future careers and academics.</p>
                        <h2>Acknowledgements 🏆</h2>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I first would like to thank my supervisors Amirul and Anusha for teaching and helping me with all of the technologies I used during my work term. I also would like to thank them for giving me a return offer for this co-op term. Lastly, I would like to thank my co-op coordinators Laura and Kate, they were really helpful during the hiring process and answered all my questions, everything was clear going into this work term thanks to them.</p>
                    </div>
                </>
            );
        default:
            return(<div>COULD NOT FOUND REPORT ID: {id}</div>);
    }
};

export default Report;
